version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bookit_user
      POSTGRES_PASSWORD: bookit_pass
      POSTGRES_DB: bookit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://bookit_user:bookit_pass@db:5432/bookit
      SECRET_KEY: dev-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: